_OWASP_KEYWORDS: dict[str, list[str]] = {
    "A01:2021-Broken Access Control": [
        "admin",
        "permission",
        "role",
        "access control",
        "authorization",
        "privilege",
        "restrict",
        "visibility",
        "can only be seen by",
        "only admins",
        "rbac",
        "acl",
    ],
    "A02:2021-Cryptographic Failures": [
        "credit card",
        "pii",
        "personal data",
        "sensitive data",
        "encrypt",
        "hash",
        "plaintext password",
        "store password",
        "ssn",
        "passport",
        "bank account",
        "private key",
        "certificate",
    ],
    "A03:2021-Injection": [
        "sql",
        "query",
        "database input",
        "user input",
        "search input",
        "command",
        "shell",
        "exec",
        "xpath",
        "ldap",
        "nosql",
        "injection",
        "sanitize input",
        "escape",
    ],
    "A04:2021-Insecure Design": [
        "threat model",
        "security design",
        "trust boundary",
        "data flow",
        "abuse case",
        "misuse case",
    ],
    "A05:2021-Security Misconfiguration": [
        "default password",
        "default config",
        "debug mode",
        "stack trace",
        "error message",
        "cors",
        "headers",
        "security headers",
        "misconfigur",
    ],
    "A06:2021-Vulnerable and Outdated Components": [
        "dependency",
        "package",
        "library",
        "version",
        "upgrade",
        "outdated",
        "vulnerable component",
        "cve",
    ],
    "A07:2021-Identification and Authentication Failures": [
        "login",
        "logout",
        "session",
        "password",
        "authentication",
        "mfa",
        "2fa",
        "token",
        "jwt",
        "oauth",
        "sso",
        "credential",
        "brute force",
        "account lockout",
    ],
    "A08:2021-Software and Data Integrity Failures": [
        "deserialization",
        "update mechanism",
        "ci/cd",
        "pipeline",
        "integrity",
        "signature",
        "checksum",
        "supply chain",
    ],
    "A09:2021-Security Logging and Monitoring Failures": [
        "audit log",
        "logging",
        "monitoring",
        "alert",
        "incident",
        "detect",
        "trace",
        "siem",
    ],
    "A10:2021-Server-Side Request Forgery": [
        "ssrf",
        "server-side request",
        "fetch url",
        "fetch external",
        "webhook url",
        "redirect url",
        "url parameter",
        "internal network",
    ],
}


def classify_owasp(text: str) -> list[str]:
    """Return OWASP Top 10 categories relevant to the given text."""
    text_lower = text.lower()
    return [
        category
        for category, keywords in _OWASP_KEYWORDS.items()
        if any(kw in text_lower for kw in keywords)
    ]
